variables:
  eureka:
    host: localHost
    port: 8761
info:
  component: Domains and Applications microservice (nearshore-employeesms)
server:
  port: 7703
spring:
  config:
    name: nearshore-employeesms
  application:
    name: nearshore-employeesms

logging:
  level:
    com.banamex.nearshore: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://${variables.eureka.host}:${variables.eureka.port}/eureka/
    registerWithEureka: true
  instance:
    preferIpAddress: true
    